name: Continuous Deployment

on:
  push:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
 
    strategy:
      matrix:
        node-version: ['19.x']

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install production dependencies
      run: npm install --only=production
    - name: SSH and Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        port: ${{ secrets.SSH_PORT }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
             cd ~/example-ci-cd
             git pull origin main
             npm install
             pm2 restart all
           