name: Continuous Deployment

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install production dependencies
        run: npm install --only=production
      - name: SSH and Deploy to server
        run: |
          echo "Deploying to server..."
          ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_PASSWORD }} 'if exist "node/example-ci-cd" ( 
            cd node/example-ci-cd
            if exist ".git" (
              git pull origin main
              npm install
              pm2 restart all
            ) else (
              cd ..
              rmdir /s /q example-ci-cd
              git clone https://github.com/myanpetra99/example-ci-cd.git
              cd example-ci-cd
              npm install
              npm run start
            )
          ) else (
            mkdir node
            cd node
            git clone https://github.com/myanpetra99/example-ci-cd.git example-ci-cd
            cd example-ci-cd
            npm install
            npm run start
          )'
